"""empty message

Revision ID: fcceeb01f067
Revises: 9ac773c0735d
Create Date: 2023-03-29 18:57:10.465169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcceeb01f067'
down_revision = '9ac773c0735d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_character_id_key', type_='unique')
        batch_op.drop_constraint('favorites_planet_id_key', type_='unique')
        batch_op.drop_constraint('favorites_user_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_unique_constraint('favorites_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('favorites_planet_id_key', ['planet_id'])
        batch_op.create_unique_constraint('favorites_character_id_key', ['character_id'])

    # ### end Alembic commands ###
